# Generated by Django 3.0.4 on 2020-04-05 03:33

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='description',
            field=froala_editor.fields.FroalaField(blank=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer_image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='answers',
            name='answer_text',
            field=froala_editor.fields.FroalaField(blank=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.Question'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=froala_editor.fields.FroalaField(),
        ),
        migrations.CreateModel(
            name='CorrectAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='exams.Answers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_question', to='exams.Question')),
            ],
        ),
    ]
